// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

// @@protoc_insertion_point(imports)

@class BaseMsg;
@class BaseMsgBuilder;
@class LocalTime;
@class LocalTimeBuilder;
@class LocalTimes;
@class LocalTimesBuilder;
@class Location;
@class LocationBuilder;
@class Locations;
@class LocationsBuilder;


typedef NS_ENUM(SInt32, Continent) {
  ContinentAfrica = 0,
  ContinentAmerica = 1,
  ContinentAntarctica = 2,
  ContinentArctic = 3,
  ContinentAsia = 4,
  ContinentAtlantic = 5,
  ContinentAustralia = 6,
  ContinentEurope = 7,
  ContinentIndian = 8,
  ContinentMideast = 9,
  ContinentPacific = 10,
};

BOOL ContinentIsValidValue(Continent value);
NSString *NSStringFromContinent(Continent value);

typedef NS_ENUM(SInt32, MCode) {
  MCodePing = 0,
  MCodePong = 1,
  MCodeMsg = 2,
};

BOOL MCodeIsValidValue(MCode value);
NSString *NSStringFromMCode(MCode value);

typedef NS_ENUM(SInt32, DayOfWeek) {
  DayOfWeekSunday = 1,
  DayOfWeekMonday = 2,
  DayOfWeekTuesday = 3,
  DayOfWeekWednesday = 4,
  DayOfWeekThursday = 5,
  DayOfWeekFriday = 6,
  DayOfWeekSaturday = 7,
};

BOOL DayOfWeekIsValidValue(DayOfWeek value);
NSString *NSStringFromDayOfWeek(DayOfWeek value);


@interface WorldClockProtocolRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface BaseMsg : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasMsg_:1;
  BOOL hasFrom_:1;
  BOOL hasTo_:1;
  BOOL hasCode_:1;
  NSString* msg;
  NSString* from;
  NSString* to;
  MCode code;
  NSMutableArray * locationArray;
  NSMutableArray * localTimeArray;
}
- (BOOL) hasCode;
- (BOOL) hasMsg;
- (BOOL) hasFrom;
- (BOOL) hasTo;
@property (readonly) MCode code;
@property (readonly, strong) NSString* msg;
@property (readonly, strong) NSString* from;
@property (readonly, strong) NSString* to;
@property (readonly, strong) NSArray * location;
@property (readonly, strong) NSArray * localTime;
- (Location*)locationAtIndex:(NSUInteger)index;
- (LocalTime*)localTimeAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (BaseMsgBuilder*) builder;
+ (BaseMsgBuilder*) builder;
+ (BaseMsgBuilder*) builderWithPrototype:(BaseMsg*) prototype;
- (BaseMsgBuilder*) toBuilder;

+ (BaseMsg*) parseFromData:(NSData*) data;
+ (BaseMsg*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BaseMsg*) parseFromInputStream:(NSInputStream*) input;
+ (BaseMsg*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BaseMsg*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (BaseMsg*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface BaseMsgBuilder : PBGeneratedMessageBuilder {
@private
  BaseMsg* resultBaseMsg;
}

- (BaseMsg*) defaultInstance;

- (BaseMsgBuilder*) clear;
- (BaseMsgBuilder*) clone;

- (BaseMsg*) build;
- (BaseMsg*) buildPartial;

- (BaseMsgBuilder*) mergeFrom:(BaseMsg*) other;
- (BaseMsgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (BaseMsgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCode;
- (MCode) code;
- (BaseMsgBuilder*) setCode:(MCode) value;
- (BaseMsgBuilder*) clearCode;

- (BOOL) hasMsg;
- (NSString*) msg;
- (BaseMsgBuilder*) setMsg:(NSString*) value;
- (BaseMsgBuilder*) clearMsg;

- (BOOL) hasFrom;
- (NSString*) from;
- (BaseMsgBuilder*) setFrom:(NSString*) value;
- (BaseMsgBuilder*) clearFrom;

- (BOOL) hasTo;
- (NSString*) to;
- (BaseMsgBuilder*) setTo:(NSString*) value;
- (BaseMsgBuilder*) clearTo;

- (NSMutableArray *)location;
- (Location*)locationAtIndex:(NSUInteger)index;
- (BaseMsgBuilder *)addLocation:(Location*)value;
- (BaseMsgBuilder *)setLocationArray:(NSArray *)array;
- (BaseMsgBuilder *)clearLocation;

- (NSMutableArray *)localTime;
- (LocalTime*)localTimeAtIndex:(NSUInteger)index;
- (BaseMsgBuilder *)addLocalTime:(LocalTime*)value;
- (BaseMsgBuilder *)setLocalTimeArray:(NSArray *)array;
- (BaseMsgBuilder *)clearLocalTime;
@end

@interface Location : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasCity_:1;
  BOOL hasContinent_:1;
  NSString* city;
  Continent continent;
}
- (BOOL) hasContinent;
- (BOOL) hasCity;
@property (readonly) Continent continent;
@property (readonly, strong) NSString* city;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (LocationBuilder*) builder;
+ (LocationBuilder*) builder;
+ (LocationBuilder*) builderWithPrototype:(Location*) prototype;
- (LocationBuilder*) toBuilder;

+ (Location*) parseFromData:(NSData*) data;
+ (Location*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Location*) parseFromInputStream:(NSInputStream*) input;
+ (Location*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Location*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Location*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface LocationBuilder : PBGeneratedMessageBuilder {
@private
  Location* resultLocation;
}

- (Location*) defaultInstance;

- (LocationBuilder*) clear;
- (LocationBuilder*) clone;

- (Location*) build;
- (Location*) buildPartial;

- (LocationBuilder*) mergeFrom:(Location*) other;
- (LocationBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (LocationBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasContinent;
- (Continent) continent;
- (LocationBuilder*) setContinent:(Continent) value;
- (LocationBuilder*) clearContinent;

- (BOOL) hasCity;
- (NSString*) city;
- (LocationBuilder*) setCity:(NSString*) value;
- (LocationBuilder*) clearCity;
@end

@interface Locations : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  NSMutableArray * locationArray;
}
@property (readonly, strong) NSArray * location;
- (Location*)locationAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (LocationsBuilder*) builder;
+ (LocationsBuilder*) builder;
+ (LocationsBuilder*) builderWithPrototype:(Locations*) prototype;
- (LocationsBuilder*) toBuilder;

+ (Locations*) parseFromData:(NSData*) data;
+ (Locations*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Locations*) parseFromInputStream:(NSInputStream*) input;
+ (Locations*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Locations*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Locations*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface LocationsBuilder : PBGeneratedMessageBuilder {
@private
  Locations* resultLocations;
}

- (Locations*) defaultInstance;

- (LocationsBuilder*) clear;
- (LocationsBuilder*) clone;

- (Locations*) build;
- (Locations*) buildPartial;

- (LocationsBuilder*) mergeFrom:(Locations*) other;
- (LocationsBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (LocationsBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray *)location;
- (Location*)locationAtIndex:(NSUInteger)index;
- (LocationsBuilder *)addLocation:(Location*)value;
- (LocationsBuilder *)setLocationArray:(NSArray *)array;
- (LocationsBuilder *)clearLocation;
@end

@interface LocalTime : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasYear_:1;
  BOOL hasMonth_:1;
  BOOL hasDayOfMonth_:1;
  BOOL hasHour_:1;
  BOOL hasMinute_:1;
  BOOL hasSecond_:1;
  BOOL hasDayOfWeek_:1;
  UInt32 year;
  UInt32 month;
  UInt32 dayOfMonth;
  UInt32 hour;
  UInt32 minute;
  UInt32 second;
  DayOfWeek dayOfWeek;
}
- (BOOL) hasYear;
- (BOOL) hasMonth;
- (BOOL) hasDayOfMonth;
- (BOOL) hasDayOfWeek;
- (BOOL) hasHour;
- (BOOL) hasMinute;
- (BOOL) hasSecond;
@property (readonly) UInt32 year;
@property (readonly) UInt32 month;
@property (readonly) UInt32 dayOfMonth;
@property (readonly) DayOfWeek dayOfWeek;
@property (readonly) UInt32 hour;
@property (readonly) UInt32 minute;
@property (readonly) UInt32 second;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (LocalTimeBuilder*) builder;
+ (LocalTimeBuilder*) builder;
+ (LocalTimeBuilder*) builderWithPrototype:(LocalTime*) prototype;
- (LocalTimeBuilder*) toBuilder;

+ (LocalTime*) parseFromData:(NSData*) data;
+ (LocalTime*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (LocalTime*) parseFromInputStream:(NSInputStream*) input;
+ (LocalTime*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (LocalTime*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (LocalTime*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface LocalTimeBuilder : PBGeneratedMessageBuilder {
@private
  LocalTime* resultLocalTime;
}

- (LocalTime*) defaultInstance;

- (LocalTimeBuilder*) clear;
- (LocalTimeBuilder*) clone;

- (LocalTime*) build;
- (LocalTime*) buildPartial;

- (LocalTimeBuilder*) mergeFrom:(LocalTime*) other;
- (LocalTimeBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (LocalTimeBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasYear;
- (UInt32) year;
- (LocalTimeBuilder*) setYear:(UInt32) value;
- (LocalTimeBuilder*) clearYear;

- (BOOL) hasMonth;
- (UInt32) month;
- (LocalTimeBuilder*) setMonth:(UInt32) value;
- (LocalTimeBuilder*) clearMonth;

- (BOOL) hasDayOfMonth;
- (UInt32) dayOfMonth;
- (LocalTimeBuilder*) setDayOfMonth:(UInt32) value;
- (LocalTimeBuilder*) clearDayOfMonth;

- (BOOL) hasDayOfWeek;
- (DayOfWeek) dayOfWeek;
- (LocalTimeBuilder*) setDayOfWeek:(DayOfWeek) value;
- (LocalTimeBuilder*) clearDayOfWeek;

- (BOOL) hasHour;
- (UInt32) hour;
- (LocalTimeBuilder*) setHour:(UInt32) value;
- (LocalTimeBuilder*) clearHour;

- (BOOL) hasMinute;
- (UInt32) minute;
- (LocalTimeBuilder*) setMinute:(UInt32) value;
- (LocalTimeBuilder*) clearMinute;

- (BOOL) hasSecond;
- (UInt32) second;
- (LocalTimeBuilder*) setSecond:(UInt32) value;
- (LocalTimeBuilder*) clearSecond;
@end

@interface LocalTimes : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  NSMutableArray * localTimeArray;
}
@property (readonly, strong) NSArray * localTime;
- (LocalTime*)localTimeAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (LocalTimesBuilder*) builder;
+ (LocalTimesBuilder*) builder;
+ (LocalTimesBuilder*) builderWithPrototype:(LocalTimes*) prototype;
- (LocalTimesBuilder*) toBuilder;

+ (LocalTimes*) parseFromData:(NSData*) data;
+ (LocalTimes*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (LocalTimes*) parseFromInputStream:(NSInputStream*) input;
+ (LocalTimes*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (LocalTimes*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (LocalTimes*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface LocalTimesBuilder : PBGeneratedMessageBuilder {
@private
  LocalTimes* resultLocalTimes;
}

- (LocalTimes*) defaultInstance;

- (LocalTimesBuilder*) clear;
- (LocalTimesBuilder*) clone;

- (LocalTimes*) build;
- (LocalTimes*) buildPartial;

- (LocalTimesBuilder*) mergeFrom:(LocalTimes*) other;
- (LocalTimesBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (LocalTimesBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray *)localTime;
- (LocalTime*)localTimeAtIndex:(NSUInteger)index;
- (LocalTimesBuilder *)addLocalTime:(LocalTime*)value;
- (LocalTimesBuilder *)setLocalTimeArray:(NSArray *)array;
- (LocalTimesBuilder *)clearLocalTime;
@end


// @@protoc_insertion_point(global_scope)
